# Generated by Django 5.0 on 2024-02-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks', models.CharField(choices=[('Burger', 'BURGER'), ('Pizza', 'PIZZA'), ('French fries', 'FRENCH FRIES'), ('Sandwich', 'SANDWICH')], max_length=50)),
                ('snack_quantity', models.IntegerField()),
                ('drinks', models.CharField(choices=[('Chocolate Milkshake', 'CHOCOLATE MILKSHAKE'), ('Mango Milkshake', 'MANGO MILKSHAKE'), ('Coffee', 'COFFEE'), ('Sprite', 'SPRITE'), ('Latte', 'LATTE')], max_length=50)),
                ('drink_quantity', models.IntegerField()),
                ('deserts', models.CharField(choices=[('Hot Chocolate', 'HOT CHOCOLATE'), ('Belgian Waffle', 'BELGIAN WAFFLE'), ('Donuts', 'DONUTS'), ('Cake', 'CAKE'), ('Icecream', 'ICECREAM')], max_length=50)),
                ('desert_quantity', models.IntegerField()),
            ],
        ),
    ]
