# Generated by Django 5.0 on 2024-02-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desert_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deserts',
            field=models.CharField(blank=True, choices=[('Hot Chocolate', 'HOT CHOCOLATE'), ('Belgian Waffle', 'BELGIAN WAFFLE'), ('Donuts', 'DONUTS'), ('Cake', 'CAKE'), ('Icecream', 'ICECREAM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='drink_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='drinks',
            field=models.CharField(blank=True, choices=[('Chocolate Milkshake', 'CHOCOLATE MILKSHAKE'), ('Mango Milkshake', 'MANGO MILKSHAKE'), ('Coffee', 'COFFEE'), ('Sprite', 'SPRITE'), ('Latte', 'LATTE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='snack_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='snacks',
            field=models.CharField(blank=True, choices=[('Burger', 'BURGER'), ('Pizza', 'PIZZA'), ('French fries', 'FRENCH FRIES'), ('Sandwich', 'SANDWICH')], max_length=50, null=True),
        ),
    ]
