# Generated by Django 5.0 on 2024-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='category',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Clothes'), (3, 'Shoes')]),
        ),
    ]
